application: ringerous
version: 2
runtime: python
api_version: 1

handlers:

- url: /index.html
  static_files: index.html
  upload: index.html
  
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
    
- url: /img/.*
  static_dir: img
  
- url: /img/(.*)
  static_files: img/\1
  upload: img/(.*)

- url: /style.css
  static_files: style.css
  upload: style.css

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
  
- url: /configure
  script: main.py
  secure: always
    
- url: /.*
  script: main.py
